config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :books, only: [:index, :show, :new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id          :bigint           not null, primary key
#  author      :string           not null
#  category    :string           not null
#  year        :integer          not null
#  owner       :boolean          default(TRUE), not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Book < ApplicationRecord
    validates :author, :category, :year, :owner, :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def index
        @books = Book.all
        render :index
    end

    def show
        @book = Book.find_by(:id => params[:id])
        if @book
            render :show
        else
            redirect_to books_path
        end
    end

    def new
        @book = Book.new
        render :new
    end

    def create
        @book = Book.new(book_params)
        if @book.save
            redirect_to book_url(@book)
        else
            render :json => @book.errors.full_messages, status: :unprocessable_entity
        end
    end

    def edit
        @book = Book.find_by(:id => params[:id])
        render :edit
    end

    def update
        @book = Book.find_by(:id => params[:id])
        if @book.update(book_params)
            redirect_to book_url(@book)
        else
            render :edit
        end
    end
    protected

    def book_params
        params.require(:books).permit(:author, :category, :year, :owner, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_book.html.erb
<li>
    <%= book.year %> by <%= book.author %>
</li>

app/views/books/_form.html.erb
<!--
    Things Need To Change:
        - actions (!done)
        - submit button (!done)
        - hidden input patch (!done)
        - values (!done)
-->

<% if action == :edit %>
    <% action_url = book_path(@book) %>
<% else %>
    <% action_url = books_url %>
<% end %>

<form action="<%= action_url %>" method="post"> 
    <% if action == :edit %>
        <input type="hidden" name="_method" value="patch">
    <% end %>
    <label for="owner" style="font-family: roboto; font-weight: bold; margin: 10px;">Owner</label>
    <select name="books[owner]" id="owner" value="<%= book.owner %>">
        <option disabled>-- Select You 🤬  --</option>
        <option value="true"
        <%= book.owner == "true" ? "selected" : "" %>>True</option>
        <option value="false"
        <%= book.owner == "false" ? "selected" : "" %>>False</option>
    </select>
    <br>
    <label for="author" style="font-family: roboto; font-weight: bold; margin: 10px;">Author</label>
    <input type="text" id="author" name="books[author]" value="<%= book.author%>">
    <br>
    <label for="category" style="font-family: roboto; font-weight: bold; margin: 10px;">Category</label>
    <select id="category" name="books[category]">
        <option disabled
        <%= book.category ? "" : "selected" %>>-- Select Me 🥺 --</option>
        <option value="Funny"
        <%= book.category == "Funny" ? "selected" : "" %>>fun</option>
        <option value="Hacking"
        <%= book.category == "Hacking" ? "selected" : "" %> >hacking</option>
        <option value="Fiction"
        <%= book.category == "Fiction" ? "selected" : "" %> >fiction</option>
    </select>
    <br>
    <label for="year" style="font-family: roboto; font-weight: bold; margin: 10px;">Year</label>
    <input type="text" id="year" name="books[year]" value="<%= book.year %>">
    <br><br>
    <label for="description" style="font-family: roboto; font-weight: bold; margin: 10px;">Description</label>
    <textarea id="description" name="books[description]">
        <%= book.description %>
    </textarea>
    <br>
    <input type="submit" value="<%= (action == :edit ) ? "Update Book" : "Add Book"%>" style="display: flex; color: green; font-size: 17px; font-family: roboto; font-weight: bold; margin: 10px;">
</form>

app/views/books/edit.html.erb
<h1>Edit Book of <%= @book.author %></h1>

<%= render 'form', book: @book, action: :edit %>

<!-- <form action="<%= book_path(@book) %>" method="post"> 
    <input type="hidden" name="_method" value="patch">
    <label for="owner" style="font-family: roboto; font-weight: bold; margin: 10px;">Owner</label>
    <select name="books[owner]" id="owner" value="<%= @book.owner %>">
        <option disabled>-- Select You 🤬  --</option>
        <option value="true"
        <%= @book.owner == "true" ? "selected" : "" %>>True</option>
        <option value="false"
        <%= @book.owner == "false" ? "selected" : "" %>>False</option>
    </select>
    <br>
    <label for="author" style="font-family: roboto; font-weight: bold; margin: 10px;">Author</label>
    <input type="text" id="author" name="books[author]" value="<%= @book.author%>">
    <br>
    <label for="category" style="font-family: roboto; font-weight: bold; margin: 10px;">Category</label>
    <select id="category" name="books[category]">
        <option disabled>-- Select Me 🥺 --</option>
        <option value="Funny"
        <%= @book.category == "Funny" ? "selected" : "" %>>fun</option>
        <option value="Hacking"
        <%= @book.category == "Hacking" ? "selected" : "" %> >hacking</option>
        <option value="Fiction"
        <%= @book.category == "Fiction" ? "selected" : "" %> >fiction</option>
    </select>
    <br>
    <label for="year" style="font-family: roboto; font-weight: bold; margin: 10px;">Year</label>
    <input type="text" id="year" name="books[year]" value="<%= @book.year %>">
    <br><br>
    <label for="description" style="font-family: roboto; font-weight: bold; margin: 10px;">Description</label>
    <textarea id="description" name="books[description]">
        <%= @book.description %>
    </textarea>
    <br>

    <input type="submit" value="Update Book" style="display: flex; color: green; font-size: 17px; font-family: roboto; font-weight: bold; margin: 10px;">

</form> -->

app/views/books/index.html.erb
<h1>All Books</h1>

<ul>
    <%= render @books %>
</ul>

app/views/books/new.html.erb
<h1>Add Books To The lists :</h1>

<%= render 'form', :action => :new, book: @book%>

<!-- <form action="/books" method="post"> 
    <label for="owner" style="font-family: roboto; font-weight: bold; margin: 10px;">Owner</label>
    <select name="books[owner]" id="owner">
        <option disabled selected>-- Select You 🤬  --</option>
        <option value="true">True</option>
        <option value="false">False</option>
    </select>
    <br>
    <label for="author" style="font-family: roboto; font-weight: bold; margin: 10px;">Author</label>
    <input type="text" id="author" name="books[author]">
    <br>
    <label for="category" style="font-family: roboto; font-weight: bold; margin: 10px;">Category</label>
    <select id="category" name="books[category]">
        <option disabled selected>-- Select Me 🥺 --</option>
        <option value="Funny">fun</label>
        <option value="Hacking">hacking</label>
        <option value="Fiction">fiction</label>
    </select>
    <br>
    <label for="year" style="font-family: roboto; font-weight: bold; margin: 10px;">Year</label>
    <input type="date" id="year" name="books[year]">
    <br><br>
    <label for="description" style="font-family: roboto; font-weight: bold; margin: 10px;">Description</label>
    <textarea id="description" name="books[description]"></textarea>
    <br>

    <input type="submit" value="Add Book" style="display: flex; color: green; font-size: 17px; font-family: roboto; font-weight: bold; margin: 10px;">

</form> -->

app/views/books/show.html.erb
<h1><%= @book.author %></h1>

<h3><%= @book.category %></h3>

<h2><%= @book.year%></h2>

<p>
    is it the owner => <%= @book.owner%>
    <br>
    <%= @book.description%>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BooksShare</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>